targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
    builders:
      # Hive CE
      hive_ce_generator:hive_ce_generator:
        enabled: true
        options:
          use_hive_registrar: false
      # JSON Serializable
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false

      # Retrofit
      retrofit_generator:
        enabled: true
